"""rename address

Revision ID: 62891d388fd8
Revises: f9131dde53b4
Create Date: 2024-06-30 19:23:07.410175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62891d388fd8'
down_revision = 'f9131dde53b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
